src/objects/MailAcceptance__c.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <label>メール送信元</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>メール件名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>受付メール</label>
    <nameField>
        <displayFormat>MA-{0000000}</displayFormat>
        <label>メール名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InboundEmailToMailAcceptance.cls
global class InboundEmailToMailAcceptance implements Messaging.InboundEmailHandler {

// このクラスは、メールの件名とメールを送信元の情報を元に、MailAcceptance__cレコードを新規作成します。

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {

        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        
        String mailFrom = email.fromAddress;
        String mailSubject = email.subject;

        List<MailAcceptance__c> mailAccs = new List<MailAcceptance__c>();
        MailAcceptance__c mailAcc = new MailAcceptance__c();

        mailAcc.Source__c = mailFrom;
        mailAcc.Subject__c = mailSubject;

        mailAccs.add(mailAcc);

        insert mailAccs;
        
        result.success = true;
        return result;
    }
    
    // テストメソッド
    public static testmethod void testUnit() {
        InboundEmailToMailAcceptance ctrl = new InboundEmailToMailAcceptance();
        
        
    }

}